### PR TITLE
Edits to nullifier post

### PR DESCRIPTION
**Pull request by lilyjordan**
I went a little heavy on the edits – feel free to take or leave as many of the changes as you want. Most of the changes were aimed at clarifying ambiguous references; reordering a couple paragraphs to make the overall direction clearer; standardizing any inconsistent notation and terminology; and making it clear which points are important and which peripheral (via emphasis, headings, sentence reorderings, deletions, and parentheticals).

# Overview of changes

## Organization
- Moved the non-interactivity section earlier, because to me it makes more sense as part of the thread of "evaluate ideas for nullifiers that aren't quite what we want". That way you don't jump from an proposal of DDH-VRF, which does fit all the criteria, to semaphores, which don't, and all the DDH-VRF stuff is grouped together.

- Moved the part where you review the properties the nullifier should have, so that it's also before you mention DDH-VRF. I kind of combined it with the non-interactivity section, interpolating the discussion of Tornado as sort of a side discussion; it would probably also work fine if you put this whole section (all four properties) after the non-interactivity section. I also gave the properties numbers and headings because I think this list is important for the reader to remember and I wanted to make it stand out and be easy to review.

- Removed the message from the first example of a bad nullifier: in the original, suggestion 1 contained the idea of using a message in the hash, but suggestion 2 didn't, which was a little confusing because it felt like we were "forgetting" an idea we'd already landed on. This way, each suggestion monotonically builds on the last.

## Pronouns
Standardized (more or less) the usage of pronouns: we, you, I, users, people. There are basically two situations where you need them: for real people (yourself, the reader, your collaborators), and for hypothetical people (users, provers, verifiers).

For real people, my rule of thumb is to use "I" to refer to the author ("I'll attempt to explain the intuition"), "you" to refer to the reader ("you might ask: isn't this a solved problem?"), and "we" to refer to the author and the reader ("we want our nullifier to have these properties"). (I noticed you were using "we" sometimes to refer to just yourself; I think the convention is to use "we" in that context for papers but "I" for blog posts).

For hypothetical people, the priorities are to 1) be consistent and 2) avoid ambiguity in what a pronoun refers to. To achieve consistency, I like to use "you" in the general sense for a hypothetical involving just one person ("you publish your nullifier"), and "you" and "I" for hypotheticals involving two people ("you send me a proof and I verify it"). This is another thing you can get away with in blog posts more than papers, because it feels more informal, but I think it's often much easier to follow.

You can also say things like "a user" or "people" or "the account", but if you do this it's really easy to overload the pronoun "they". For instance: "[W]e need some way of ensuring that anonymous accounts can link their actions together to collect reputation or be bannable." It takes some thought to understand whether this sentence means that multiple accounts can all link their actions together into one group, or that a given account can link its actions together (the correct meaning). So I changed this to "[Y]ou’d need some way of requiring each anonymous account to link all its actions together, so you could track its reputation or ban it if you had to."

The other thing is to make sure that the real-person meanings of "you", "I", and "we" don't get confused with the hypothetical-person meanings; in cases where these were too close together, I used alternatives like "an account". When in doubt, you can also fall back on Alice/Bob or Peggy/Victor notation.

In the last paragraph, I left the "we" phrasing because I figured it meant you plus collaborators, but if you're just using it to refer to yourself as you would in a paper, you'd probably want to switch it to I. Ideally if you're referring to collaborators/coauthors you would just start out the paragraph by naming them, like "Kobi Gurkan and I..." or "With collaborators at 0xPARC, I...". Same with "We will have a formal proof of this in a paper very soon!".

## Definitions and explanations
Broadly, on explainer posts like this, my principle is to prefer the “problem -> solution” framing to the “solution -> motivation” framing. With definitions, prefer “problem area -> desirable properties of a construction -> rigorous definition of the construction"; in particular, I prefer to explain a concept and then say "this is called [term]", rather than saying the term and then explaining what it means, so the reader never has to temporarily hold a meaningless word in their head. I think your draft mostly does this already on the macro level, which is good. For the most part, I just changed some individual paragraphs to also follow this structure.

Another thing I think is good and that you shouldn't change is the color-coded math. massively underrated imo.

I substituted concrete examples for generalizations where possible (for instance, extended some mentions of particular airdrop use cases throughout the entire explanation of ZK airdrops and the need for nulllifiers).

## Opening paragraph
The original intro seemed like it had been adapted from an abstract, so I changed it to go more directly into what you're talking about, taking less time to summarize the state of the whole field. The other thing I like to do in blog intros that you can't do in abstracts is to not give away spoilers: in an abstract you kind of have to say where you're going to end up, whereas with blogs, I think it's more engaging to keep the suspense and just jump into the problem, implying in the title of the post that you're proposing a solution, without immediately summarizing what the solution will be.

## Consistency nits
- Standardized some spelling and capitalization: there was some inconsistency between zk/ZK/ZK-SNARK/zkSNARK, so I standardized on ZK and zkSNARK; feel free to choose something else, as long as it's consistent. Also I changed “ZK proof of knowledge” to “ZK proof” but tell me if I’m wrong and this is actually a term of art.
- Standardized the inline Latex formatting, mostly with regard to descriptions of hashing; sometimes hash functions were in Latex and sometimes they weren't, so I put them all in Latex, but wrapped in \text{}. Also replaced a few headings where you were using a screenshot where plaintext probably sufficed.
- Both "private key" and "secret key" terminology were being used, so I changed it to use "secret key" everywhere. I don't love this, because "private key" feels more standard to me, but I can see how "pk" becomes ambiguous in the math otherwise. Maybe you know a better convention for this. (Also I'm mostly sure that "private key" and "secret key" are supposed to be interchangeable here, but if that isn't what you meant and there is actually some implied difference, then definitely change it back, and maybe clarify what that is).
- There was one footnote and everything else was links, so I'm just turning the footnote into a link too, unless there's some reason why you wanted it as a footnote. There was also (in the markdown) an extra floating footnote at the bottom that didn't have anything linking to it, so I took it out, but feel free to link to it wherever you meant to.

## Minor style stuff
- Spell out single-digit numbers (two instead of 2)
- Spell out acronyms on first reference (zero knowledge, decisional Diffie-Hellman) unless they're for really common terms (DAO) or stand for a meaningless list of names (BLS)

# Things I didn't fix but you might want to

## Styling
This is slightly out of scope, but when reading the post on your website, I noticed that it felt somewhat difficult on the eyes. I think this is mainly caused by the contrast between the dark background and the white text being a little too high: it felt much more readable when I changed the text color to something like #959191. The other thing is that the Garamond font is a little bit cramped, so I might recommend either choosing a different font or adjusting the letter-spacing up to something in the 0.03-0.06rem range.

## Possibly-unfamiliar concepts
There were a few things I had to google; these might benefit from having a brief refresher on the definition or a link to an explainer:
- MACI
- discrete log problem
- signature schemes (just a link is fine for each): Goh-Jarecki, Chaum-Pederson, BLS; also maybe whatever paper originally proposed DDH-VRF, I couldn't easily find one by googling.
- Aztec
- dark pools
- UTXOs
- semaphores
- relayers

## Explanations that still feel confusing to me
I did my best to clarify explanations that initially seemed confusing, but you should read over everything to make sure my changes don't accidentally imply anything incorrect. There were a few remaining bits where I'm still not quite sure what you meant and am not confident enough that I'd be able to correctly guess, so I'm leaving these in case you want to revise them yourself.

### "If we could use a pairing-friendly curve, we could have just used the deterministic BLS signature scheme and skipped this whole exercise!"

You might want to clarify this more – how much would be skipped if we could use BLS? Like, what's the relationship between VRFs, BLS, and pairing-friendly curves. Doesn't have to be long, but I'm unclear on which part BLS would replace.

### "So a user could simply hash a random string to start with, and use another hash of that preimage as their nullifier from then on (this is what tornado.cash uses for withdrawal claims)."

This might be worth devoting another sentence to. I think it would be clearer what's going on if you spell out the scheme a little more precisely, with particular emphasis on why allowing interactivity permits this kind of scheme. (In particular, what does the preimage refer to? You also might want to place more emphasis on how the user has to commit publicly to a particular nullifier before using it e.g. for withdrawals).

### "Third, Tornado reveals your nullifier in plaintext in-browser, allowing Chrome and malicious extensions to access it."

Is this required by interactivity (as opposed to just a Tornado design flaw)? If so, might be useful to spell out why, and what about non-interactive systems would allow them to not do this.

### "And fourth, interactivity doesn’t work with certain applications, like ZK airdrops, because it would open the protocol to sybil attacks and spam."

It's not obvious to me why – might want to spell this out too. What would an attack look like?

### "This makes it possible to check in a wallet or an extension – the enclave generating proof knows the public key, but doesn’t know the secret key."

Not sure what "the enclave generating proof" refers to, or whether it should say "the enclave generating the proof"; anyway I thought the verifier was outside the enclave? like what is the enclave referring to here

### "higher-bit keypairs on similar algorithms"
Similar to what? Maybe link out to something here, although this isn't crucial to your main point, so it could also just be deleted.

### the quantum tradeoff graphic
I left this because on principle I think it's good to split up blocks of text with images and diagrams, but the layout of the graphic took me a while to understand; you might want to revise it to clarify that the relationship between the concepts in it is like "if you want {noninteractivity, quantum secrecy} you should use {ZK nulllifiers, semaphores}".

### "This can be done with a ZK airdrop to unlinked accounts (which then keeps anonymous votes linked), or just proofs from a relayer (where you can choose to link your votes or not)."
Wasn't sure what this sentence was trying to say: what links to what? Who's choosing whether to link votes, where does the relayer come in, why would/wouldn't you link? Who's "you" – the airdropper or the airdroppee?

### Paragraph beginning "We can also build more user-friendly dark pools..."
This whole paragraph was confusing to me. In particular: "instead of leaking the nullifier string in plaintext on the frontend from a server via the website" – what exactly is happening in this case? "Systems like Aztec currently get this via encrypting the random nullifier string with someone’s encryption key, but these nullifiers let you do this on the Ethereum base curve itself, which doesn’t usually support encryption." – the mental model I'm getting from this feels fuzzy, it might help to be more explicit with your compare/contrast here. (Also, "someone" feels ambiguous – I assume you encrypt your nullifier with your own key, but this sounds like it's implying there's some third party who does the encryption? or am I misunderstanding and that is what you meant to say?)

Hope this is helpful. Let me know if you have any questions!

### CODE REVIEW

**Comment by Divide-By-0** [comment]
Cool, ty! Here are my responses

> "If we could use a pairing-friendly curve, we could have just used the deterministic BLS signature scheme and skipped this whole exercise!"

For this, I'm trying to say that most pairing friendly curve signature algorithms can be made easily unique, so you can just use hash(sig) directly as the nullifier, for instance with BLS. I bring up BLS because the construction is very similar to what I propose. It's more that Ethereum sigs arent deterministic than that theyre not pairing friendly!

> "So a user could simply hash a random string to start with, and use another hash of that preimage as their nullifier from then on (this is what tornado.cash uses for withdrawal claims)."

Ah yean random string = preimage here, good clarification (the tornado construction is here: https://docs.google.com/presentation/d/1lou0dhoekxTaMKRekpXlSMcALs_SH_JcEWHoXoOKlas/edit#slide=id.p slides 21-26) with a video explainer here https://youtu.be/2lGFj0Exfb8?t=1171

> "Third, Tornado reveals your nullifier in plaintext in-browser, allowing Chrome and malicious extensions to access it." Is this required by interactivity (as opposed to just a Tornado design flaw)? If so, might be useful to spell out why, and what about non-interactive systems would allow them to not do this.

Yeah, you need this because of the random string/preimage thing I alluded to earlier: there needs to be some random string shown to the user that is not in a secure enclave/wallet. Non interactive systems only use your wallet, so all secrets are kept much more securely.

> "And fourth, interactivity doesn’t work with certain applications, like ZK airdrops, because it would open the protocol to sybil attacks and spam." It's not obvious to me why – might want to spell this out too. What would an attack look like? 

That's fair -- I think poorly implemented it does this (and there's some a16z example that did this) but in reality probably a well implemented thing is fine.

> "This makes it possible to check in a wallet or an extension – the enclave generating proof knows the public key, but doesn’t know the secret key." Not sure what "the enclave generating proof" refers to, or whether it should say "the enclave generating the proof"; anyway I thought the verifier was outside the enclave? like what is the enclave referring to here

*ah sorry enclave generating the proof. and yeah sorry this isn't even in the enclave. basically what i'm saying is like, either the website or wallet or app generating the proof then cannot get your secret key, if i.e. the enclave isn't capable of generating a proof.

> "higher-bit keypairs on similar algorithms" Similar to what? Maybe link out to something here, although this isn't crucial to your main point, so it could also just be deleted.

oh like if you just make ethereum ecdsa like, 1024 bits isntead of 256 then you need a 4x as big quantum computer to break it and thats probably like several extra years of security

> the quantum tradeoff graphic I left this because on principle I think it's good to split up blocks of text with images and diagrams, but the layout of the graphic took me a while to understand; you might want to revise it to clarify that the relationship between the concepts in it is like "if you want {noninteractivity, quantum secrecy} you should use {ZK nulllifiers, semaphores}".

Yeahh it's not ideal, just a screenshot from my slide; i'm not really sure how to lay this image out well. feel free to delete or propose another image for me to do or even can make an image you think would be more useful for understanding?

> "This can be done with a ZK airdrop to unlinked accounts (which then keeps anonymous votes linked), or just proofs from a relayer (where you can choose to link your votes or not)." Wasn't sure what this sentence was trying to say: what links to what? Who's choosing whether to link votes, where does the relayer come in, why would/wouldn't you link? Who's "you" – the airdropper or the airdroppee?

oh sorry you is the claimer of the airdrop. you need some sort of relaying service because the mempool requires balance in the account to pay the gas to show the tx, and fresh accounts probably don't have this balance, so basically what happens is you send it to a rich relayer instead, who pays the gas for you and puts the zk proof in the mempool, but takes an equivalent cut of the gas they paid, of the claimed token value instead (plus a fee)

> Paragraph beginning "We can also build more user-friendly dark pools..."

i think aztec v1/zcash constructs a new keypair based off of your current private key on a curve with encryption (i.e. ed25519), and then when you move transfer money to a recipient on aztec with ethereum keys, you encrypt your nullifier with the recipient key so that it's discoverable by them and only them. the recipient then needs to scrape the chain to be able to discover secret txs sent to them by trying to decrypt each nullifier and checking if its for them. i actually forget how our scheme improves on this so maybe lets cut this lol

**Comment by Divide-By-0** [comment]
MACI : https://privacy-scaling-explorations.github.io/maci/ and https://ethresear.ch/t/minimal-anti-collusion-infrastructure/5413

discrete log problem - https://en.wikipedia.org/wiki/Discrete_logarithm

signature schemes (just a link is fine for each): Goh-Jarecki, Chaum-Pederson, BLS; also maybe whatever paper originally proposed DDH-VRF, I couldn't easily find one by googling.

each of those papers are probably on eprint iacr or scihub
https://toc.cryptobook.us/book.pdf pdf pagees 860-861 are good for ddh-vrf, this RFC is also good: https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-vrf-07

Aztec dark pools - can cut this paragraph

UTXOs - the original bitcoin paper is ok, and the intro of this: https://eprint.iacr.org/2021/340.pdf is pretty good
semaphores - slides 13 and onwards: https://docs.google.com/presentation/d/1lou0dhoekxTaMKRekpXlSMcALs_SH_JcEWHoXoOKlas/edit#slide=id.p and corresponding part in https://youtu.be/2lGFj0Exfb8

relayers - command f relayer in this: https://github.com/stealthdrop/stealthdrop

**Comment by lilyjordan** [comment]
cool, just added another round of edits based on these.

here's an diagram I sketched up for the quantum stuff, you could use something like this

diagram

Double-check one more time to make sure you like this and that the changes are accurate and everything – you might want to give these a little extra scrutiny since they're the parts that were initially most complicated.

**Comment by Divide-By-0** [comment]
Cool! I think the blog post looks great -- I think I forgot to enable latex or something in hugo so let me add that in this week. Also that new diagram looks great, but the post isn't updated to include that -- did you want to replace those? I also added you to this repo so you should be able to make changes/branches/etc directly here!

**Comment by lilyjordan** [comment]
oh yeah sorry, didn't initially see the media directory in the repo

**Comment by lilyjordan** [comment]
one typo - "intergrations" -> "integrations" in the last paragraph

**Comment by Divide-By-0** [comment]
Cool! I was able to fix the media and latex and publish, and I just fixed the last typo on main.

**Pull request merged**
